# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NGINX_VERSION=stable
ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine as base

WORKDIR /home/node/app

COPY package.json ./

COPY next.config.ts ./

COPY .npmrc ./

RUN npm install -g npm@11.5.2

RUN npm install --force

COPY . .

RUN npm run build

FROM nginx:${NGINX_VERSION} as nginx

COPY --from=base /home/node/app/out /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
