name: Test CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write
  actions: write

env:
  NPM_VERSION: '22'
  REGISTRY_URL: 'https://npm.pkg.github.com'
  REPO_NAME: ${{ github.event.repository.name }}
  NEXT_PUBLIC_UI_URL: http://localhost:3000
  NEXT_PUBLIC_HEADER_TITEL: docs
  NEXT_PUBLIC_GIT_REPO_URL: https://github.com/munirmardinli-dev/docs

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub Repository
        run: |
          git clone https://github.com/munirmardinli-dev/docs.git
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: npm
          cache-dependency-path: 'docs/package-lock.json'
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            docs/node_modules
            docs/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        working-directory: ./docs
        run: npm ci
      - name: Remove .env.local
        working-directory: ./docs
        run: |
          rm -f .env.local
          echo ".env.local removed if it existed"
          ls -la
      - name: Copy MDX Files
        working-directory: ./docs
        run: |
          cp -r ./*.mdx src/app/ || true
          cp -r ./*.md src/app/ || true
      - name: Create default page
        run: |
          mkdir -p src/app
          echo "---
          title: 'test'
          description: "Beschreibung der Seite"
          author: "Munir Mardinli"
          date: "2025-08-27"
          ---
          # Test" > src/app/page.mdx
      - name: Run build
        working-directory: ./docs
        run: |
          npm run build
          ls -la
        env:
          NODE_ENV: production
          NEXT_PUBLIC_UI_URL: ${{ env.NEXT_PUBLIC_UI_URL }}
          NEXT_PUBLIC_HEADER_TITEL: ${{ env.NEXT_PUBLIC_HEADER_TITEL }}
          NEXT_PUBLIC_GIT_REPO_URL: ${{ env.NEXT_PUBLIC_GIT_REPO_URL }}
